#%RAML 1.0 DataType
type: object
properties:
  Salaried:
    type: string
    required: false
  Self Employed Professional:
    type: string
    required: false
  Self Employed Non Professional:
    type: string
    required: false
  Micro Enterprise:
    type: string
    required: false
  Small Enterprise:
    type: string
    required: false
  Medium Enterprise:
    type: string
    required: false
  Large Enterprise:
    type: string
    required: false
  Other Enterprises:
    type: string
    required: false
  Others:
    type: string
    required: false
  Cash Salaried:
    type: string
    required: false