#%RAML 1.0 DataType
type: object
properties:
  Digital Alliance:
    type: string
  Digital Direct:
    type: string
    required: false
  Connector:
    type: string
    required: false
  
  