#%RAML 1.0 DataType
type: object
properties:
  Self construction:
    type: string
    required: false
  Direct allotment from development Authority:
    type: string
    required: false
  Purchase from Builder:
    type: string
    required: false
  Purchase from Co-Operative Society:
    type: string
    required: false
  Land + Construction:
    type: string
    required: false
  Re-Sale:
    type: string
    required: false
  Top Up:
    type: string
    required: false
  Allotment Transfer:
    type: string
    required: false
  Loan Against Property:
    type: string
    required: false
  Balance Transfer:
    type: string
    required: false
  Commercial Purchase:
    type: string
    required: false